version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: taskmanager-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=task_manager
      - DB_USERNAME=taskuser
      - DB_PASSWORD=taskpass123
    volumes:
      - .:/var/www

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: taskmanager-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    depends_on:
      - backend
    working_dir: /app
    volumes:
      - ./frontend:/app

  db:
    image: mysql:8.0
    container_name: taskmanager-db
    restart: always
    environment:
      MYSQL_DATABASE: task_manager
      MYSQL_USER: taskuser
      MYSQL_PASSWORD: taskpass123
      MYSQL_ROOT_PASSWORD: rootpass123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: 